name: cyfishon
description: "Flutter-приложение для сообщества рыбаков Кипра"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  
  # Навигация
  go_router: ^14.6.2
  
  # Хранилище
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  path: ^1.9.0
  
  # Геолокация
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  
  # Сеть
  http: ^1.2.2
  connectivity_plus: ^6.1.0
  
  # Утилиты
  intl: ^0.20.2
  yaml: ^3.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Ассеты
  assets:
    - pubspec.yaml
  #   - assets/images/
  #   - assets/icons/
  
  # Шрифты
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
